//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuManager.FrameWorkModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public Promotion()
        {
            this.PromotionDetails = new HashSet<PromotionDetail>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long PromotionTypeId { get; set; }
        public decimal Rate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual PromotionType PromotionType { get; set; }
        public virtual ICollection<PromotionDetail> PromotionDetails { get; set; }
    }
}
