//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuManager.FrameWorkModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SKUCS : DbContext
    {
        public SKUCS()
            : base("server=.;database=SKU;Integrated Security=SSPI;")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Promotion> Promotion { get; set; }
        public DbSet<PromotionDetails> PromotionDetails { get; set; }
        public DbSet<PromotionType> PromotionType { get; set; }
        public DbSet<Sku> Sku { get; set; }
    }
}
